"""Validate all translations and emit the dependency-free browser i18n bundle."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = [
    {"code": "en", "label": "English", "short": "EN", "htmlLang": "en"},
    {"code": "de", "label": "Deutsch", "short": "DE", "htmlLang": "de"},
    {"code": "es", "label": "Español", "short": "ES", "htmlLang": "es"},
    {"code": "ru", "label": "Русский", "short": "RU", "htmlLang": "ru"},
    {"code": "pt", "label": "Português", "short": "PT", "htmlLang": "pt"},
    {"code": "vi", "label": "Tiếng Việt", "short": "VI", "htmlLang": "vi"},
    {"code": "zh", "label": "中文", "short": "中文", "htmlLang": "zh-CN"},
]
catalogs = {}
for item in LANGUAGES:
    catalogs[item["code"]] = json.loads((ROOT / "fruit-machine-ui/locales" / (item["code"] + ".json")).read_text(encoding="utf-8"))
reference = catalogs["en"]
for code, entries in catalogs.items():
    assert entries.keys() == reference.keys(), f"{code}: translation keys differ"
    for key, value in entries.items():
        assert isinstance(value, str) and value.strip(), f"{code}/{key}: empty translation"
        assert sorted(re.findall(r"\{[A-Za-z]+\}", value)) == sorted(re.findall(r"\{[A-Za-z]+\}", reference[key])), f"{code}/{key}: placeholder mismatch"

runtime = """
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.GraftI18n = api;
})(typeof window !== 'undefined' ? window : globalThis, function () {
  'use strict';
  const locales = __LOCALES__;
  const messages = __MESSAGES__;
  function normalize(value) {
    if (typeof value !== 'string') return null;
    const code = value.trim().toLowerCase().replace(/_/g, '-').split('-')[0];
    return Object.prototype.hasOwnProperty.call(messages, code) ? code : null;
  }
  function t(locale, key, variables = {}) {
    const code = normalize(locale) || 'en';
    const template = messages[code][key] ?? messages.en[key] ?? key;
    return Object.entries(variables).reduce((text, [name,value]) =>
      text.replaceAll('{' + name + '}', String(value)), template);
  }
  return Object.freeze({locales:Object.freeze(locales), messages:Object.freeze(messages), normalize, t});
});
"""
runtime = runtime.replace("__LOCALES__", json.dumps(LANGUAGES, ensure_ascii=False, separators=(",", ":")))
runtime = runtime.replace("__MESSAGES__", json.dumps(catalogs, ensure_ascii=False, separators=(",", ":")))
(ROOT / "fruit-machine-ui/i18n.js").write_text("// Generated by scripts/build-locales.py; edit locales/*.json instead.\n" + runtime.lstrip(), encoding="utf-8")
print(f"Built {len(catalogs)} complete locales × {len(reference)} messages")

