const { chromium, launchOptions } = require('./browser-runtime.cjs');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const errors=[];
(async()=>{
 const browser=await chromium.launch(launchOptions);
 try {
  const page=await browser.newPage({viewport:{width:1080,height:1080},reducedMotion:'reduce',locale:'zh-CN'});
  page.on('pageerror',e=>errors.push(e.message));
  // Force a known wind triple only in this test browser, never in production.
  await page.addInitScript(()=>{crypto.getRandomValues=array=>{array.fill(0);return array;};});
  await page.goto('http://localhost:4199/',{waitUntil:'domcontentloaded'});
  assert.equal(await page.locator('.pay-button').count(),8);
  assert.equal(await page.locator('.garden-node').count(),24);
  assert.equal(await page.locator('#startButton').isDisabled(),true);
  assert.equal(await page.locator('#wealthTitle').innerText(),'余额');
  assert.equal(await page.locator('#wealthValue').innerText(),'1000000.00');
  assert.equal(await page.locator('#rtpValue').innerText(),'97.00%');
  assert.match(await page.locator('.footnote').innerText(),/97%/);
  const first=page.locator('.pay-button').first();
  await first.click();
  assert.equal(await first.locator('.lane-stake').innerText(),'01');
  const box=await first.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
  await page.mouse.down();await page.waitForTimeout(900);await page.mouse.up();
  const count=Number(await first.locator('.lane-stake').innerText());
  assert.ok(count>=6,'long hold repeats');
  await page.waitForTimeout(220);assert.equal(Number(await first.locator('.lane-stake').innerText()),count,'release stops increments');
  await page.locator('#clearBetsButton').click();
  assert.equal(await first.locator('.lane-stake').innerText(),'00');
  await first.click();await page.locator('#startButton').click();
  await page.waitForFunction(()=>document.querySelector('#startLabel').textContent==='收取收成');
  assert.equal(await page.locator('#wealthValue').innerText(),'999999.00');
  assert.equal(await page.locator('#prizeValue').innerText(),'3.20','one-credit three-hit payout is exact');
  assert.equal(await page.locator('.garden-node.lit').count(),12);
  await page.locator('#startButton').click();
  assert.equal(await page.locator('#wealthValue').innerText(),'1000002.20','collect once');
  // Exercise the changed two-hit tier, not just the unchanged three-hit one.
  await page.evaluate(()=>{let season=0;crypto.getRandomValues=array=>{array.fill(season++%3===2?1:0);return array;};});
  await page.locator('#startButton').click();
  await page.waitForFunction(()=>document.querySelector('#startLabel').textContent==='收取收成');
  assert.equal(await page.locator('#prizeValue').innerText(),'1.52','97% two-hit payout');
  await page.locator('#startButton').click();
  assert.equal(await page.locator('#wealthValue').innerText(),'1000002.72','exact two-hit collection');
  await page.evaluate(()=>{crypto.getRandomValues=array=>{array.fill(0);return array;};});
  await page.locator('#bloomButton').click();await page.locator('#layoutButton').click();
  await page.locator('#startButton').click();
  await page.waitForFunction(()=>document.querySelector('#startLabel').textContent==='收取收成');
  assert.equal(await page.locator('#prizeValue').innerText(),'7.76');
  await page.locator('#toast.show').waitFor({state:'hidden'});
  await page.screenshot({path:'reference-analysis/graft-desktop.png',fullPage:true});
  await page.locator('#languageButton').click();await page.locator('[data-locale="en"]').click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.locator('h1').innerText(),'Graft Garden');
  assert.equal(await page.locator('#wealthTitle').innerText(),'Balance');
  assert.equal(await page.locator('#rtpValue').innerText(),'97.00%');
  assert.match(await page.locator('.footnote').innerText(),/97%/);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no mobile horizontal overflow');
  await page.screenshot({path:'reference-analysis/graft-mobile-en.png',fullPage:true});
  await page.locator('#rulesButton').click();assert.match(await page.locator('#dialogBody').innerText(),/0.97/);await page.locator('#closeDialog').click();
  console.log('PASS standalone: visible RTP97% in both languages, exact 1.52/3.20/7.76 payouts, zero bets, hold/release/clear, collection, mobile layout.');
  if (process.env.STANDALONE_ONLY === '1') return;
  const deployed=JSON.parse(fs.readFileSync('casino-sdk/casino-sdk/simulator/local-node/deployed.json','utf8'));
  const addr=deployed.games.find(g=>g.name==='GraftGardenGame').address;
  const host=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
  await host.addInitScript(()=>localStorage.setItem('graft.locale','zh'));
  host.on('pageerror',e=>errors.push(e.message));
  await host.goto('http://localhost:3300/?game='+encodeURIComponent('http://localhost:4199/')+'&gameAddress='+addr,{waitUntil:'domcontentloaded'});
  const frame=host.frameLocator('iframe');
  await frame.locator('#connectionLabel').filter({hasText:'Casino SDK'}).waitFor({timeout:30000});
  assert.equal(await frame.locator('#wealthTitle').innerText(),'余额');
  await frame.locator('.pay-button').first().click();
  await host.getByLabel('Wallet status (live)').first().selectOption('disconnected');
  await frame.locator('#connectionLabel').filter({hasText:'连接钱包'}).waitFor();
  assert.equal(await frame.locator('#startButton').isDisabled(),true,'disconnected host cannot fall back to demo');
  await host.getByLabel('Wallet status (live)').first().selectOption('ready');
  await frame.locator('#connectionLabel').filter({hasText:'Casino SDK'}).waitFor();
  await frame.locator('#startButton').click();
  await frame.locator('#roundStatus').filter({hasText:/条下注路径命中|未达到收成条件/}).waitFor({timeout:60000});
  await frame.locator('#verifyButton').click();
  const json=JSON.parse(await frame.locator('#dialogBody pre').innerText());
  assert.equal(json.source,'contract');assert.ok(json.sessionId);assert.equal(json.decimals,18);
  assert.equal(json.theoreticalRtp,'97%');
  assert.equal(json.stakes[0],'1000000000000000000');
  assert.ok(json.randomness || json.randomnessRequests?.length>0 || json.verification?.requests?.length>0,JSON.stringify(json));
  await frame.locator('#closeDialog').click();
  console.log('PASS official simulator: Penpal + manifest, wallet guard, openSession, VRF, decoded contract payout, reveal and verification. Session '+json.sessionId);
  // Open another real round, reload iframe while its pending key is present.
  if(await frame.locator('#startLabel').innerText()==='继续')await frame.locator('#startButton').click();
  await frame.locator('#startButton').click();
  const gameFrame=host.frames().find(f=>f.url().startsWith('http://localhost:4199'));
  await gameFrame.waitForFunction(()=>Object.keys(sessionStorage).some(k=>k.startsWith('graft.pending:') && sessionStorage.getItem(k)!=='null'));
  await gameFrame.goto('http://localhost:4199/',{waitUntil:'domcontentloaded'});
  await frame.locator('#roundStatus').filter({hasText:/条下注路径命中|未达到收成条件/}).waitFor({timeout:60000});
  await frame.locator('#verifyButton').click();
  const recovered=JSON.parse(await frame.locator('#dialogBody pre').innerText());
  assert.notEqual(recovered.sessionId,json.sessionId);
  assert.equal(recovered.stakes[0],'1000000000000000000');
  await frame.locator('#closeDialog').click();
  console.log('PASS iframe reload: recovered real pending/settled round '+recovered.sessionId+' without submitting another wager.');
  assert.deepEqual(errors,[]);
  fs.writeFileSync('reference-analysis/GRAFT_BROWSER_VERIFICATION.json',JSON.stringify({testedAt:new Date().toISOString(),rtpBps:9700,displayedRtp:'97.00%',testedPayouts:['1.52','3.20','7.76'],standalone:true,longHold:true,exactMoney:true,mobileWidth:390,localSdkSession:json.sessionId,recoveredSession:recovered.sessionId,pageErrors:errors},null,2));
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
